# Generated by Django 5.1.4 on 2025-01-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('portada', models.ImageField(upload_to='portadas_series/')),
                ('link_ver', models.URLField()),
            ],
        ),
    ]
