# Generated by Django 5.1.4 on 2025-01-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='link_ver',
            new_name='trailer_url',
        ),
    ]
