# Generated by Django 5.1.4 on 2025-01-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_rename_link_ver_serie_trailer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='trailer_url',
            new_name='video_url',
        ),
    ]
